### PR TITLE
consolidating the project resources folder

### PR DESCRIPTION
**Pull request by jdizoglio**
There were 2 BoxBrowseSDKResources folders. I moved this info.plist into the BoxBrowseSDKResources containing the icons and deleted the duplicate folder.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @jdizoglio, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by boxtcarpel** [comment]
+1

:package:

**Comment by RicoYao** [comment]
lgtm

**Comment by RicoYao** [comment]
@jdizoglio can this be merged?

**Comment by sowmiya** [comment]
Closing this for now as it is too old, will reopen if issue persists.

**Pull request closed without merging**
