### PR TITLE
IOS-10020 - load images directly from resources

### PR DESCRIPTION
**Pull request by adempsey**

### CODE REVIEW

**Comment by adempsey** [comment]
@boxtcarpel

**Comment by boxcla** [comment]
Verified that @adempsey has signed the CLA. Thanks for the pull request!

**Comment by boxtcarpel** [comment]
Any project changes to how the resources get included in the framework?

**Comment by boxtcarpel** [comment]
+2 for the code changes, awesome! Go frameworks!

**Comment by adempsey** [comment]
Looks like the resources were already being imported correctly, just needed to update the code to reflect that. Doesn't seem like any project changes should be necessary.

**Comment by boxtcarpel** [comment]
Awesome +2
:twisted_rightwards_arrows:

**Pull request merged**
